# Generated by Django 5.0.4 on 2024-06-25 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_likepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(default='06d6d2c2-acfb-4f26-82a9-29a403545565', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.post'),
        ),
    ]
